// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkCore10Sample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "City.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.ToJson("Location");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4ab0f01-510d-4d3b-b8f6-af75cb20b777"),
                            City = "Taggia",
                            FirstName = "Marco",
                            IsDeleted = false,
                            LastName = "Minerva",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("776ebb4a-c658-4892-8ec3-4ec2d09fadeb"),
                            City = "Topolinia",
                            FirstName = "Mickey",
                            IsDeleted = false,
                            LastName = "Mouse",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("39b186d5-44b4-417a-9f37-d959b45de89d"),
                            City = "Paperopoli",
                            FirstName = "Donald",
                            IsDeleted = false,
                            LastName = "Duck",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("baffeb2b-2257-48c4-8f45-ec20a300c922"),
                            City = "Topolinia",
                            FirstName = "Minnie",
                            IsDeleted = true,
                            LastName = "Mouse",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("c98b3e97-5c55-4f11-bdd8-aecfa0610718"),
                            City = "Topolinia",
                            FirstName = "Goofy",
                            IsDeleted = false,
                            LastName = "Goof",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("f1b45738-f211-46e0-b95c-24b894a1f429"),
                            City = "Paperopoli",
                            FirstName = "Daisy",
                            IsDeleted = false,
                            LastName = "Duck",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("9ae944bb-bba4-4ac6-9c4d-248c221f627b"),
                            City = "Topolinia",
                            FirstName = "Pluto",
                            IsDeleted = true,
                            LastName = "Dog",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("302dc1b9-6220-425b-b243-7b7fcbbc63ea"),
                            City = "Paperopoli",
                            FirstName = "Scrooge",
                            IsDeleted = false,
                            LastName = "McDuck",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("e8f2b8dc-c1ca-44a2-b7d2-e31a19012e79"),
                            City = "Paperopoli",
                            FirstName = "Huey",
                            IsDeleted = false,
                            LastName = "Duck",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f31fb820-b524-4efe-b6f2-7415080f5d7b"),
                            City = "Paperopoli",
                            FirstName = "Dewey",
                            IsDeleted = false,
                            LastName = "Duck",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("5d4194d4-3905-4646-bf33-432afeef867e"),
                            City = "Topolinia",
                            FirstName = "Clarabelle",
                            IsDeleted = true,
                            LastName = "Cow",
                            TenantId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
